### ISSUE TITLE
Cannot find container dockerdrupal8_default

### ISSUE THREAD

**Issue by TigerWolf** [universityofadelaide/docker-drupal8#6] opened 2016-06-28 02:59 UTC
docker: Error response from daemon: network dockerdrupal8_default not found.
See 'docker run --help'.
Error response from daemon: No such container: dockerdrupal8_utility

**Comment by pingers** [comment] 2016-06-28 03:44
Not sure why it's not working. I'm using Docker version 1.11.2, build b9f10c9 on linux though...

Try purging? purge.sh

**Comment by TigerWolf** [comment] 2016-06-28 04:16
Should purge have an error?

```
$ ./purge.sh
Loading vars for docker machine.
No stopped containers
Error response from daemon: network dockerdrupal8_default not found
```

EDIT:

```
$ docker network ls                                                                                                                                                                                                                                            
NETWORK ID          NAME                    DRIVER              SCOPE
c3a5f6641ab1        bridge                  bridge              local
ef77a6b239dc        dockerdrupal8_default   bridge              local
ec512420cab4        host                    host                local
8fe98c11a445        none                    null                local
```

```
$ docker network rm dockerdrupal8_default 
Error response from daemon: network dockerdrupal8_default has active endpoints
```

I restarted docker and then I was able to delete the network:

```
docker network rm dockerdrupal8_default   
dockerdrupal8_default
```

Still had a problem when starting ./dsh

```
$ ./start.sh 
Creating network "dockerdrupal8_default" with the default driver
Starting dockerdrupal8_web_1
Starting dockerdrupal8_mysql_1
Starting dockerdrupal8_memcache_1
Starting dockerdrupal8_mail_1
$ ./dsh.sh  
Loading vars for docker machine.
docker: Error response from daemon: network dockerdrupal8_default not found.
See 'docker run --help'.
Error response from daemon: No such container: dockerdrupal8_utility
```

**Comment by TigerWolf** [comment] 2016-06-28 05:45
Updated my debugging @pingers

**Comment by pingers** [comment] 2016-06-28 13:37
Guessing it's related to Mac, seeing I can't reproduce it.

**Comment by TigerWolf** [comment] 2016-06-29 06:49
Fixed by running

`eval "$(docker-machine env default)"`

**Comment by pingers** [comment] 2016-06-29 07:03
start.sh isn't including common.sh at all... this is a deviation from other repositories. I'm not surprised it's not working correctly. Probably need to run setup_docker_machine? @bart88

**Comment by bart88** [comment] 2016-06-29 07:38
@pingers I'll fix this as a separate issue

**Comment by bart88** [comment] 2016-06-30 01:27
#9 adds the common.sh to start.sh which will setup docker machine for OS's that require it

**Comment by singularo** [comment] 2021-07-10 00:27
Oooh, this is ancient, closing.

**Closed as completed by singularo** 2021-07-10 00:27 UTC
Labels: bug
